repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: ["--strict"]

  # Format JS/CSS/HTML (optional, requires Node under the hood)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies: ["prettier@3.3.3"]
        files: '\\.(js|css|html|mjs)$'

  # Run Django tests on pre-push to avoid breaking changes
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check (CI parity)
        entry: uv run ruff check .
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: django-tests
        name: Run Django tests
        entry: uv run python snorkelforecast/manage.py test
        language: system
        pass_filenames: false
        stages: [pre-push]
