"""
Django settings for snorkelforecast project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY: Configure via environment in production
# SECRET_KEY: required in production, fallback dev key for local use
_DEV_FALLBACK_SECRET = "dev-insecure-snorkelforecast-key"
SECRET_KEY = os.getenv("SECRET_KEY", _DEV_FALLBACK_SECRET)

# DEBUG: default true for local dev, override to false in prod
DEBUG = str(os.getenv("DEBUG", "true")).lower() in {"1", "true", "yes", "on"}

# Hosts: comma-separated in env, with sensible defaults for dev/prod
_default_hosts = [
    "snorkelforecast.com",
    "www.snorkelforecast.com",
    "localhost",
    "127.0.0.1",
    "192.168.1.129",
    "100.90.123.85",
]
ALLOWED_HOSTS = [
    h.strip() for h in os.getenv("ALLOWED_HOSTS", ",".join(_default_hosts)).split(",") if h.strip()
]

# Additional security: CSRF trusted origins (comma-separated)
_csrf_env = os.getenv("CSRF_TRUSTED_ORIGINS", "")
if _csrf_env:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_env.split(",") if o.strip()]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django_watchfiles",
    "django_browser_reload",
    # "django.contrib.gis",  # Temporarily disabled - enable with PostGIS in production
    "conditions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = "snorkelforecast.snorkelforecast.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "conditions.context_processors.language_context",
            ],
        },
    },
]

WSGI_APPLICATION = "snorkelforecast.snorkelforecast.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Use /persistent path for DB when PRODUCTION env var is truthy
IS_PRODUCTION = str(os.getenv("PRODUCTION", "")).lower() in {"1", "true", "yes", "on"}

# In production, ensure a real SECRET_KEY is provided
if IS_PRODUCTION and (not SECRET_KEY or SECRET_KEY == _DEV_FALLBACK_SECRET):
    raise RuntimeError("SECRET_KEY environment variable must be set in production.")
db_name: Path | str
if IS_PRODUCTION:
    db_name = "/persistent/db.sqlite3"
else:
    db_name = BASE_DIR / "db.sqlite3"

# Database configuration (upgrade to PostGIS in production)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": db_name,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", "English"),
    ("es", "Español"),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

WHITENOISE_MAX_AGE = 31536000  # 1 year

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Caching
# Use a shared file cache by default so the background scheduler can warm data
# for Gunicorn workers. LocMemCache is process-local, which makes page and
# forecast cache hits unreliable in production.
if IS_PRODUCTION:
    _default_cache_dir = "/persistent/django-cache"
else:
    _default_cache_dir = BASE_DIR / ".django-cache"

_cache_backend = os.getenv(
    "CACHE_BACKEND",
    "django.core.cache.backends.filebased.FileBasedCache",
)
_cache_location = os.getenv("CACHE_LOCATION", str(_default_cache_dir))

CACHES = {
    "default": {
        "BACKEND": _cache_backend,
        "LOCATION": _cache_location,
    }
}

# Default cache TTL (seconds) for decorators; override with CACHE_TTL env
CACHE_TTL = int(os.getenv("CACHE_TTL", "300"))

# Forecast pages are expensive to rebuild because they can refresh upstream
# weather data and persist history. Cache the rendered HTML longer than generic
# pages so anonymous traffic does not repeatedly hit that path.
LOCATION_PAGE_CACHE_TTL = int(os.getenv("LOCATION_PAGE_CACHE_TTL", "21600"))

# OSM Service settings
OSM_CACHE_TTL = int(os.getenv("OSM_CACHE_TTL", "86400"))  # 24 hours
OSM_REQUEST_DELAY = float(os.getenv("OSM_REQUEST_DELAY", "1.0"))  # seconds between requests

# Forecast cache settings (6 hours for weather data)
FORECAST_CACHE_TTL = int(os.getenv("FORECAST_CACHE_TTL", "21600"))  # 6 hours
FORECAST_CACHE_STALE_TTL = int(os.getenv("FORECAST_CACHE_STALE_TTL", "86400"))  # 24 hours
FORECAST_CACHE_NEGATIVE_TTL = int(os.getenv("FORECAST_CACHE_NEGATIVE_TTL", "1800"))  # 30 minutes
FORECAST_REQUEST_TIMEOUT = float(os.getenv("FORECAST_REQUEST_TIMEOUT", "5.0"))

# IndexNow: instantly notify Bing, Yandex, DuckDuckGo, Seznam and Naver of new/
# changed URLs. The key is public by design (hosted at /<key>.txt). Override per
# environment with INDEXNOW_KEY.
INDEXNOW_KEY = os.getenv("INDEXNOW_KEY", "be177cbd2ec82163c3306faf2a57923d")
SITE_BASE_URL = os.getenv("SITE_BASE_URL", "https://snorkelforecast.com")
