# Generated by Django 5.2.4 on 2026-06-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("conditions", "0003_importtile_osmspot"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationForecastSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("country_slug", models.CharField(blank=True, db_index=True, max_length=64)),
                ("city_slug", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "snapshot_key",
                    models.CharField(
                        help_text="Lookup key for row", max_length=255, unique=True
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("horizon_hours", models.IntegerField(default=72)),
                ("snapshot_hours", models.JSONField(default=list)),
                ("generated_at", models.DateTimeField()),
                (
                    "valid_until",
                    models.DateTimeField(help_text="After this time the snapshot is stale"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="The snorkeling location this snapshot belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_snapshots",
                        to="conditions.snorkellocation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["location", "horizon_hours"],
                        name="conditions_loc_foreca_6f9c1_idx",
                    ),
                    models.Index(
                        fields=["country_slug", "city_slug", "horizon_hours"],
                        name="conditions_loc_foreca_d4fc2_idx",
                    ),
                    models.Index(fields=["valid_until"], name="conditions_loc_foreca_c8b3e_idx"),
                ],
            },
        ),
    ]

