# Generated by Codex on 2026-06-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conditions", "0004_add_locationforecastsnapshot"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="locationforecastsnapshot",
            new_name="conditions__locatio_cfbdcd_idx",
            old_name="conditions_loc_foreca_6f9c1_idx",
        ),
        migrations.RenameIndex(
            model_name="locationforecastsnapshot",
            new_name="conditions__country_8544c0_idx",
            old_name="conditions_loc_foreca_d4fc2_idx",
        ),
        migrations.RenameIndex(
            model_name="locationforecastsnapshot",
            new_name="conditions__valid_u_1bd383_idx",
            old_name="conditions_loc_foreca_c8b3e_idx",
        ),
        migrations.AlterField(
            model_name="locationforecastsnapshot",
            name="snapshot_hours",
            field=models.JSONField(default=list, help_text="Forecast payload for the horizon"),
        ),
        migrations.AddIndex(
            model_name="forecasthour",
            index=models.Index(
                fields=["country_slug", "time"],
                name="cond_fh_country_time_idx",
            ),
        ),
    ]
