# Generated by Django 5.2.4 on 2026-06-28 11:00

import conditions.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0007_seed_maui_snorkel_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='snorkellocation',
            name='best_time',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='snorkellocation',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='snorkellocation',
            name='exposure',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='snorkellocation',
            name='local_region',
            field=models.CharField(blank=True, help_text='Local coast/neighborhood, e.g. Kaanapali or South Maui', max_length=100),
        ),
        migrations.AddField(
            model_name='snorkellocation',
            name='shore_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('min_rating', models.CharField(choices=[('fair', 'Fair or better'), ('good', 'Good or better'), ('excellent', 'Excellent only')], default='good', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('token', models.CharField(default=conditions.models._alert_token, max_length=96, unique=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to='conditions.snorkellocation')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'min_rating'], name='cond_alert_active_rating_idx'), models.Index(fields=['location', 'is_active'], name='cond_alert_location_idx')],
                'constraints': [models.UniqueConstraint(fields=('email', 'location'), name='uniq_alert_subscription_email_location')],
            },
        ),
    ]
