from zlib import crc32

from django.db import migrations


HAWAII_SPOTS = [
    {
        "name": "Hawaii",
        "city_slug": "hawaii",
        "area_slug": "",
        "region": "Hawaii",
        "local_region": "Hawaiian Islands",
        "latitude": 20.7500,
        "longitude": -156.5000,
        "location_type": "marine_park",
        "difficulty": "Varies by island",
        "best_time": "Morning before trade winds build",
        "exposure": "Island chain with sharply different windward and leeward exposure",
        "shore_type": "Hawaii snorkel hub",
        "is_popular": True,
        "description": (
            "Hawaii snorkel report hub for comparing Maui, Oahu, Kauai and Big "
            "Island conditions before choosing a beach."
        ),
    },
    {
        "name": "Maui",
        "city_slug": "maui",
        "area_slug": "hawaii",
        "region": "Hawaii",
        "local_region": "Maui",
        "latitude": 20.7984,
        "longitude": -156.3319,
        "location_type": "island",
        "difficulty": "Varies by beach",
        "best_time": "Morning before trade winds build",
        "exposure": "Island-wide: north, west, and south exposures vary sharply",
        "shore_type": "Island hub",
        "is_popular": True,
        "description": (
            "Maui is a daily snorkel report hub for comparing West, Northwest "
            "and South Maui spots. Use the beach reports below for site-level "
            "calls because wind, swell and visibility can vary sharply between bays."
        ),
    },
    {
        "name": "Kapalua Bay",
        "city_slug": "kapalua-bay",
        "area_slug": "maui",
        "region": "Maui, Hawaii",
        "local_region": "West Maui",
        "latitude": 21.0008,
        "longitude": -156.6660,
        "location_type": "bay",
        "difficulty": "Easy",
        "best_time": "Morning",
        "exposure": "Sheltered west-facing bay",
        "shore_type": "Sandy beach with reef along both points",
        "description": "Protected West Maui bay with family-friendly entries, reef fish and turtles.",
    },
    {
        "name": "Honolua Bay",
        "city_slug": "honolua-bay",
        "area_slug": "maui",
        "region": "Maui, Hawaii",
        "local_region": "Northwest Maui",
        "latitude": 21.0145,
        "longitude": -156.6385,
        "location_type": "bay",
        "difficulty": "Moderate",
        "best_time": "Summer mornings",
        "exposure": "Northwest-facing bay; avoid north swell",
        "shore_type": "Rocky bay entry",
        "description": "Marine life conservation district with excellent reef when the bay is calm and blue.",
    },
    {
        "name": "Kaanapali Black Rock",
        "city_slug": "kaanapali-black-rock",
        "area_slug": "maui",
        "region": "Maui, Hawaii",
        "local_region": "Kaanapali",
        "latitude": 20.9290,
        "longitude": -156.6947,
        "location_type": "beach",
        "difficulty": "Easy",
        "best_time": "Morning",
        "exposure": "West-facing beach; wind and swell wrap around the point",
        "shore_type": "Sandy beach and lava-rock point",
        "description": "Accessible snorkel spot at Black Rock with turtles, reef fish and cliff-jump crowds.",
    },
    {
        "name": "Napili Bay",
        "city_slug": "napili-bay",
        "area_slug": "maui",
        "region": "Maui, Hawaii",
        "local_region": "West Maui",
        "latitude": 21.0030,
        "longitude": -156.6670,
        "location_type": "bay",
        "difficulty": "Easy",
        "best_time": "Morning",
        "exposure": "West-facing crescent bay",
        "shore_type": "Sandy beach with rocky points",
        "description": "Beginner-friendly crescent bay with turtles and reef along the points.",
    },
    {
        "name": "Ulua Mokapu",
        "city_slug": "ulua-mokapu",
        "area_slug": "maui",
        "region": "Maui, Hawaii",
        "local_region": "Wailea",
        "latitude": 20.6874,
        "longitude": -156.4437,
        "location_type": "reef",
        "difficulty": "Easy to moderate",
        "best_time": "Early morning",
        "exposure": "Southwest-facing reef; avoid strong south swell",
        "shore_type": "Sandy entries with reef shelves",
        "description": "Twin Wailea beaches with reef shelves, turtles and reliable morning snorkeling.",
    },
    {
        "name": "Maluaka Turtle Town",
        "city_slug": "maluaka-turtle-town",
        "area_slug": "maui",
        "region": "Maui, Hawaii",
        "local_region": "South Maui",
        "latitude": 20.6496,
        "longitude": -156.4444,
        "location_type": "beach",
        "difficulty": "Easy to moderate",
        "best_time": "Morning",
        "exposure": "South-facing beach; avoid south swell and afternoon wind",
        "shore_type": "Sandy beach with lava-rock reef",
        "description": "South Maui turtle area with reef fish and clearer water on calm mornings.",
    },
    {
        "name": "Molokini Crater",
        "city_slug": "molokini-crater",
        "area_slug": "maui",
        "region": "Maui, Hawaii",
        "local_region": "Offshore Maui",
        "latitude": 20.6314,
        "longitude": -156.4956,
        "location_type": "reef",
        "difficulty": "Boat only",
        "best_time": "Early boat trips",
        "exposure": "Offshore crater; wind exposure increases quickly",
        "shore_type": "Offshore volcanic crater reef",
        "description": "Clear-water offshore crater with excellent visibility when morning winds stay light.",
    },
    {
        "name": "Ahihi Kinau",
        "city_slug": "ahihi-kinau",
        "area_slug": "maui",
        "region": "Maui, Hawaii",
        "local_region": "South Maui",
        "latitude": 20.6111,
        "longitude": -156.4367,
        "location_type": "marine_park",
        "difficulty": "Moderate",
        "best_time": "Calm mornings",
        "exposure": "Southwest lava coast; avoid surge",
        "shore_type": "Lava-rock entry and protected reef",
        "description": "Protected lava-rock reef reserve where calm wind and low surge matter.",
    },
    {
        "name": "Oahu",
        "city_slug": "oahu",
        "area_slug": "hawaii",
        "region": "Hawaii",
        "local_region": "Oahu",
        "latitude": 21.4389,
        "longitude": -158.0001,
        "location_type": "island",
        "difficulty": "Varies by beach",
        "best_time": "Morning",
        "exposure": "South, west, east and north shores vary by season",
        "shore_type": "Island hub",
        "is_popular": True,
        "description": "Oahu snorkel report hub for comparing protected bays, west-side reefs and seasonal shore exposure.",
    },
    {
        "name": "Hanauma Bay",
        "city_slug": "hanauma-bay",
        "area_slug": "oahu",
        "region": "Oahu, Hawaii",
        "local_region": "East Honolulu",
        "latitude": 21.2690,
        "longitude": -157.6938,
        "location_type": "marine_park",
        "difficulty": "Easy",
        "best_time": "Early reserved entry",
        "exposure": "Sheltered volcanic bay; exposed during stronger east swell",
        "shore_type": "Sandy bay with shallow reef",
        "is_popular": True,
        "description": "Protected marine life conservation bay and Oahu's best-known beginner snorkel spot.",
    },
    {
        "name": "Sharks Cove",
        "city_slug": "sharks-cove",
        "area_slug": "oahu",
        "region": "Oahu, Hawaii",
        "local_region": "North Shore",
        "latitude": 21.6497,
        "longitude": -158.0634,
        "location_type": "cove",
        "difficulty": "Moderate",
        "best_time": "Summer mornings",
        "exposure": "North Shore; unsafe during winter surf",
        "shore_type": "Lava-rock tide pools and cove",
        "description": "North Shore lava cove with excellent summer snorkeling and dangerous winter surf.",
    },
    {
        "name": "Electric Beach",
        "city_slug": "electric-beach",
        "area_slug": "oahu",
        "region": "Oahu, Hawaii",
        "local_region": "West Oahu",
        "latitude": 21.3582,
        "longitude": -158.1304,
        "location_type": "reef",
        "difficulty": "Advanced",
        "best_time": "Calm early mornings",
        "exposure": "West-side open coast; currents can be strong",
        "shore_type": "Sandy entry to offshore reef",
        "description": "Advanced west-side reef known for clear water, turtles and dolphin sightings.",
    },
    {
        "name": "Lanikai Beach",
        "city_slug": "lanikai-beach",
        "area_slug": "oahu",
        "region": "Oahu, Hawaii",
        "local_region": "Kailua",
        "latitude": 21.3925,
        "longitude": -157.7153,
        "location_type": "beach",
        "difficulty": "Easy",
        "best_time": "Morning before trades",
        "exposure": "Windward east shore",
        "shore_type": "Sandy beach and patch reef",
        "description": "Windward beach with pretty water and patchy reef; best before trade winds build.",
    },
    {
        "name": "Kahe Point",
        "city_slug": "kahe-point",
        "area_slug": "oahu",
        "region": "Oahu, Hawaii",
        "local_region": "West Oahu",
        "latitude": 21.3563,
        "longitude": -158.1286,
        "location_type": "reef",
        "difficulty": "Advanced",
        "best_time": "Calm mornings",
        "exposure": "Open west coast; watch current and boat traffic",
        "shore_type": "Sandy entry to reef drop-off",
        "description": "Also called Electric Beach, Kahe Point is a clear-water reef for confident swimmers.",
    },
    {
        "name": "Kauai",
        "city_slug": "kauai",
        "area_slug": "hawaii",
        "region": "Hawaii",
        "local_region": "Kauai",
        "latitude": 22.0964,
        "longitude": -159.5261,
        "location_type": "island",
        "difficulty": "Varies by beach",
        "best_time": "Morning",
        "exposure": "North and south shore seasons differ strongly",
        "shore_type": "Island hub",
        "is_popular": True,
        "description": "Kauai snorkel report hub for comparing north-shore summer reefs and south-shore beaches.",
    },
    {
        "name": "Anini Beach",
        "city_slug": "anini-beach",
        "area_slug": "kauai",
        "region": "Kauai, Hawaii",
        "local_region": "North Shore",
        "latitude": 22.2220,
        "longitude": -159.4517,
        "location_type": "beach",
        "difficulty": "Easy",
        "best_time": "Morning",
        "exposure": "Reef-protected north shore; avoid high surf",
        "shore_type": "Long sandy beach behind barrier reef",
        "description": "Long protected reef lagoon that is often one of Kauai's calmer snorkel options.",
    },
    {
        "name": "Poipu Beach",
        "city_slug": "poipu-beach",
        "area_slug": "kauai",
        "region": "Kauai, Hawaii",
        "local_region": "South Shore",
        "latitude": 21.8738,
        "longitude": -159.4572,
        "location_type": "beach",
        "difficulty": "Easy",
        "best_time": "Morning",
        "exposure": "South shore; avoid strong south swell",
        "shore_type": "Sandy beach with protected cove",
        "description": "Popular south-shore beach with protected pockets, reef fish and frequent turtles.",
    },
    {
        "name": "Tunnels Beach",
        "city_slug": "tunnels-beach",
        "area_slug": "kauai",
        "region": "Kauai, Hawaii",
        "local_region": "North Shore",
        "latitude": 22.2247,
        "longitude": -159.5622,
        "location_type": "reef",
        "difficulty": "Moderate",
        "best_time": "Summer mornings",
        "exposure": "North shore; avoid winter surf",
        "shore_type": "Outer reef and sandy beach",
        "description": "Scenic north-shore reef with excellent summer snorkeling and serious winter surf exposure.",
    },
    {
        "name": "Lydgate Beach",
        "city_slug": "lydgate-beach",
        "area_slug": "kauai",
        "region": "Kauai, Hawaii",
        "local_region": "East Kauai",
        "latitude": 22.0378,
        "longitude": -159.3358,
        "location_type": "beach",
        "difficulty": "Easy",
        "best_time": "Morning",
        "exposure": "Rock-walled lagoon; still check surge",
        "shore_type": "Protected rock-walled swimming area",
        "description": "Family-friendly protected lagoon with easier entries and reef fish.",
    },
    {
        "name": "Big Island",
        "city_slug": "big-island",
        "area_slug": "hawaii",
        "region": "Hawaii",
        "local_region": "Hawaii Island",
        "latitude": 19.5429,
        "longitude": -155.6659,
        "location_type": "island",
        "difficulty": "Varies by beach",
        "best_time": "Morning",
        "exposure": "Kona coast is often calmer; east side is windier",
        "shore_type": "Island hub",
        "is_popular": True,
        "description": "Big Island snorkel report hub for Kona reefs, protected bays and lava-rock entries.",
    },
    {
        "name": "Kealakekua Bay",
        "city_slug": "kealakekua-bay",
        "area_slug": "big-island",
        "region": "Big Island, Hawaii",
        "local_region": "Kona Coast",
        "latitude": 19.4790,
        "longitude": -155.9300,
        "location_type": "bay",
        "difficulty": "Boat, kayak or hike",
        "best_time": "Morning",
        "exposure": "Protected Kona bay",
        "shore_type": "Bay reef and marine sanctuary",
        "description": "Marine sanctuary with some of Hawaii's clearest water and healthiest reef.",
    },
    {
        "name": "Two Step Honaunau",
        "city_slug": "two-step-honaunau",
        "area_slug": "big-island",
        "region": "Big Island, Hawaii",
        "local_region": "South Kona",
        "latitude": 19.4200,
        "longitude": -155.9130,
        "location_type": "reef",
        "difficulty": "Moderate",
        "best_time": "Morning",
        "exposure": "Kona lava coast; avoid surge",
        "shore_type": "Lava-rock step entry",
        "description": "Celebrated Kona lava-rock reef with clear water, reef fish and frequent dolphins offshore.",
    },
    {
        "name": "Kahaluu Beach Park",
        "city_slug": "kahaluu-beach-park",
        "area_slug": "big-island",
        "region": "Big Island, Hawaii",
        "local_region": "Kailua-Kona",
        "latitude": 19.5793,
        "longitude": -155.9725,
        "location_type": "beach",
        "difficulty": "Easy",
        "best_time": "Morning",
        "exposure": "Protected Kona reef",
        "shore_type": "Sandy/rocky entry with shallow reef",
        "description": "Accessible Kona snorkel beach with reef fish, turtles and beginner-friendly facilities.",
    },
    {
        "name": "Anaehoomalu Bay",
        "city_slug": "anaehoomalu-bay",
        "area_slug": "big-island",
        "region": "Big Island, Hawaii",
        "local_region": "Waikoloa",
        "latitude": 19.9149,
        "longitude": -155.8870,
        "location_type": "bay",
        "difficulty": "Easy",
        "best_time": "Morning",
        "exposure": "West-facing resort bay",
        "shore_type": "Sandy bay with reef patches",
        "description": "Waikoloa resort bay, often called A-Bay, with easy access and patch reef snorkeling.",
    },
]


def seed_hawaii_spots(apps, schema_editor):
    SnorkelLocation = apps.get_model("conditions", "SnorkelLocation")
    for spot in HAWAII_SPOTS:
        defaults = {
            "osm_id": -int(crc32(f"usa:{spot['city_slug']}".encode("utf-8"))),
            "osm_type": "manual",
            "name": spot["name"],
            "country": "USA",
            "region": spot["region"],
            "local_region": spot.get("local_region", ""),
            "area_slug": spot.get("area_slug", ""),
            "latitude": spot["latitude"],
            "longitude": spot["longitude"],
            "timezone": "Pacific/Honolulu",
            "description": spot["description"],
            "location_type": spot["location_type"],
            "difficulty": spot.get("difficulty", ""),
            "best_time": spot.get("best_time", ""),
            "exposure": spot.get("exposure", ""),
            "shore_type": spot.get("shore_type", ""),
            "is_popular": spot.get("is_popular", False),
            "is_verified": True,
            "quality_score": 0.9,
            "source": "manual",
            "osm_tags": {},
        }
        SnorkelLocation.objects.update_or_create(
            country_slug="usa",
            city_slug=spot["city_slug"],
            defaults=defaults,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0008_snorkellocation_best_time_snorkellocation_difficulty_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_hawaii_spots, migrations.RunPython.noop),
    ]
