name: CI

on:
  pull_request:
  push:
    branches: [ master, main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies (app + dev)
        run: |
          uv sync --frozen --group dev

      - name: Lint (ruff)
        run: |
          uv run ruff format --check .
          uv run ruff check .

      - name: Pre-commit (all files)
        run: |
          uv run pre-commit run --all-files

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: snorkelforecast.snorkelforecast.settings
        run: |
          uv run python snorkelforecast/manage.py test -v 2

